### ISSUE TITLE
err

### ISSUE THREAD

**Issue by ibyteyou** [vue-bulma/cleave#1]
Cleave.js?fc82:92 Uncaught Error: Please include phone-type-formatter.{country}.js lib
My opts = { phone: true, phoneRegionCode: 'RU' }

**Comment by fundon** [comment]
@patriciussanctus Look at example: https://github.com/fundon/vue-admin/blob/master/src/components/pages/UI/Form.vue#L332-L334
https://github.com/fundon/vue-admin/blob/master/src/components/pages/UI/Form.vue#L301-L302

**Comment by alexandrasmith00** [comment]
Also having this same error.  The examples that were linked to aren't functional

**Comment by Mouvedia** [comment]
@fundon both links are dead.
