### ISSUE TITLE
Problem with v-model

### ISSUE THREAD

**Issue by alexandrasmith00** [vue-bulma/cleave#10]
I thought this issue had been closed, but cleave no longer works when using v-model.  I'm using vue@^2.3.3 and vue-cleave@^1.2.0.

Here is the typical cleave component. When adding the v-model field, the cleave formatting no longer works and without the v-model field, it does.

`<cleave v-model="date" placeholder="Delivery Date" :options="{ date: true,  datePattern: [ 'm', 'd', 'Y'] }"></cleave>`

**Comment by ikbalmoh** [comment]
try #8

**Comment by luventa** [comment]
I'm trying to fix this issue now. Sorry for replying late.

- Update 1 
I published v1.2.1 which will make cleave work. Now I'm dealing with incorrect data binding issue.

- Update 2
Issue fixed. v1.2.2 is published.
This is my test [demo](https://github.com/luventa/cleave-demo)

**Comment by Cholowao** [comment]
#8 #15
