### ISSUE TITLE
Making this component compatible with Vue 2.0 and parent v-model

### ISSUE THREAD

**Issue by Ataraxy** [vue-bulma/cleave#2]
I was having trouble syncing the input value from this child component with the v-model of the parent. This was the solution to make it work for me with Vue 2.0.

`<input :type="type" :value="value" @input="$emit('input', $event.target.value)" />`

**Comment by fundon** [comment]
Thanks, very useful!

Vue 2.0 drops the two way binding.
If the parent wants to sync the value of the child, it just needs to listen some events from child's events.

**Comment by fundon** [comment]
Welcome, PR! :)

**Comment by goldfire** [comment]
I just opened a PR similar to this (based on the example in the Vue 2.0 guide): https://github.com/vue-bulma/cleave/pull/3.

**Comment by fundon** [comment]
Landed in v1.1.1. Thanks to @goldfire.
